### ISSUE TITLE
Cannot delete from import map if service name includes a `/` in it

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/import-map-deployer#14]
Having a `/` in a service name is pretty common, for namespacing. Example: `@openmrs/root-config`.

But deleting something from the import map doesn't work if you attempt to do so, probably because the `/` is interpreted to mean a different part of the route entirely.

**Comment by nhumrich** [comment]
Ya, I'm not really sure how to resolve this issue. Have you tried encoding the  slash?

We should probably check for slash at creation and prevent it. Literally any other character for namespacing besides `/` or `?` would work.

**Comment by frehner** [comment]
> Ya, I'm not really sure how to resolve this issue. Have you tried encoding the slash?
> 
> We should probably check for slash at creation and prevent it. Literally any other character for namespacing besides `/` or `?` would work.

It's the standard in JS land to use the `@company/package` format though, so I think encoding it would probably be the better route rather than preventing it.

**Comment by nhumrich** [comment]
does `@company` really need to be in the name? Is there a situation where multiple companies code would be deployed to the same location? I dont mind if we can get this to work, I am just trying to understand.

**Comment by frehner** [comment]
It’s more to prevent name clashes for base names, eg if I happen to name a microservice “react” then there will be some problems with which react am I importing from?

**Comment by joeldenning** [comment]
Encoding the `/` as `%2F` worked.

<img width="1237" alt="Screen Shot 2019-06-17 at 11 57 17 PM" src="https://user-images.githubusercontent.com/5524384/59636287-d0a47100-915b-11e9-8ad9-7e347fb543e6.png">
