### ISSUE TITLE
NPX example doesn't work

### ISSUE THREAD

**Issue by zleight1** [CanopyTax/import-map-deployer#21]
I'm setting up the recommended single-spa workflow and in testing this tool I got some weird behavior.

If you run the example `npx import-map-deployer config.json` (inside another project *not this one cloned*) you will get a 404 error from the NPM registry:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/import-map-deployer - Not found
npm ERR! 404
npm ERR! 404  'import-map-deployer@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Either you're assuming the user is running it with a private mirror, or something else is my guess.

If you could clarify what the proper way to run this from Node is, with a little more context it would probably solve this issue.

If you need more information or would like me to clarify more, let me know. Thanks for the awesome work on all the single-spa ecosystem so far!

**Comment by joeldenning** [comment]
This is just a bug - we forgot to publish this to npm. There are several groups using this project in production, but all are currently using it via docker.

I'll publish this to npm and let you know when it's working

**Comment by joeldenning** [comment]
Try it now! I fixed this in https://github.com/CanopyTax/import-map-deployer/commit/b2d415b20b2f5bbfd36a41888b71d58acc3f85f6 and https://github.com/CanopyTax/import-map-deployer/commit/4030e7a4f7e1e3999f288f5d3e2a264c64315a3f

**Comment by zleight1** [comment]
Amazing! This is a big help to our CD workflow!
