### ISSUE TITLE
Rename this project to import-map-deployer

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/import-map-deployer#8]
sofe has been superceded by [import maps](https://github.com/WICG/import-maps), and I'm now encouraging the single-spa community to use this project to manage deployments. As such, I think the name import-map-deployer would be easier for people to remember and understand. Thoughts?

@nhumrich @blittle @TheMcMurder @frehner

**Comment by nhumrich** [comment]
Wow.... What a boring name....

**Comment by joeldenning** [comment]
Done
